-- NOT APPLIED: auto-review blocked activation pending explicit approval of the
-- A-plan reminder-only operation with 397 unsaved candidates and 56 setup issues.
-- New DB only; no grants, DDL, invoices or business-row edits.
BEGIN;
SET LOCAL timezone='Asia/Tokyo';
SET LOCAL statement_timeout='60s';
SET LOCAL lock_timeout='5s';
LOCK TABLE public.customers,public.projects,public.contracts,public.annual_records,public.maintenance_responses,public.periodic_maintenance,public.prospects,public.attachments,public.billing_units,public.billing_operations,public.billing_recipient_plans,public.billing_recipient_plan_overrides,public.billing_unit_events,public.ownership_transfers,public.invoice_import_evidence,public.invoice_recipient_initializations,public.billing_migration_acceptances,public.billing_runtime_control,public.project_management_events,public.ageful_migration_target IN SHARE ROW EXCLUSIVE MODE;
DO $$
DECLARE baseline jsonb; after_state jsonb;
BEGIN
 baseline:=jsonb_build_object('customers',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.customers t),'projects',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.projects t),'contracts',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.contracts t),'annual_records',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.annual_records t),'maintenance_responses',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.maintenance_responses t),'periodic_maintenance',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.periodic_maintenance t),'prospects',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.prospects t),'attachments',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.attachments t),'billing_units',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_units t),'billing_operations',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_operations t),'billing_recipient_plans',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_recipient_plans t),'billing_recipient_plan_overrides',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_recipient_plan_overrides t),'billing_unit_events',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_unit_events t),'ownership_transfers',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.ownership_transfers t),'invoice_import_evidence',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.invoice_import_evidence t),'invoice_recipient_initializations',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.invoice_recipient_initializations t),'billing_migration_acceptances',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_migration_acceptances t),'billing_runtime_control',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_runtime_control t),'project_management_events',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.project_management_events t));
 IF (SELECT count(*) FROM public.ageful_migration_target)<>1
 OR NOT EXISTS(SELECT 1 FROM public.ageful_migration_target WHERE project_ref='ufawaiddntqqbjhycbxn')
 OR encode(sha256(convert_to(baseline::text,'UTF8')),'hex')<>'aeb7f0ae0b80cebf64bd794ef786500a06d40de5b46a89625b9b0a3f8223a487'
 OR NOT EXISTS(SELECT 1 FROM auth.users WHERE id='9a4b877c-d73d-4c37-a902-40c521240d06' AND email='admin@ageful.co.jp')
 OR EXISTS(SELECT 1 FROM public.billing_runtime_control)
 THEN RAISE EXCEPTION 'Cutover baseline/target/owner mismatch'; END IF;
 INSERT INTO public.billing_runtime_control(owner_user_id,enabled,future_schedule_coverage_verified,cutover_on)
 VALUES('9a4b877c-d73d-4c37-a902-40c521240d06',true,true,'2026-09-27');
 after_state:=jsonb_build_object('customers',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.customers t),'projects',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.projects t),'contracts',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.contracts t),'annual_records',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.annual_records t),'maintenance_responses',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.maintenance_responses t),'periodic_maintenance',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.periodic_maintenance t),'prospects',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.prospects t),'attachments',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.attachments t),'billing_units',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_units t),'billing_operations',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_operations t),'billing_recipient_plans',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_recipient_plans t),'billing_recipient_plan_overrides',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_recipient_plan_overrides t),'billing_unit_events',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_unit_events t),'ownership_transfers',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.ownership_transfers t),'invoice_import_evidence',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.invoice_import_evidence t),'invoice_recipient_initializations',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.invoice_recipient_initializations t),'billing_migration_acceptances',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_migration_acceptances t),'billing_runtime_control',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.billing_runtime_control t),'project_management_events',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb) FROM public.project_management_events t));
 IF (baseline-'billing_runtime_control') IS DISTINCT FROM (after_state-'billing_runtime_control')
 THEN RAISE EXCEPTION 'Business/audit rows changed'; END IF;
END $$;
SET LOCAL request.jwt.claim.sub='9a4b877c-d73d-4c37-a902-40c521240d06';
SET LOCAL request.jwt.claims='{"sub":"9a4b877c-d73d-4c37-a902-40c521240d06","role":"authenticated"}';
SET LOCAL request.headers='{"x-ageful-client":"ledger-v1"}';
SET LOCAL ROLE authenticated;
DO $$ DECLARE s jsonb; BEGIN
 s:=public.billing_runtime_snapshot();
 IF s->>'ready'<>'true' OR jsonb_array_length(s->'units')<>32 OR s->>'cutover_on'<>'2026-09-27'
 THEN RAISE EXCEPTION 'Runtime acceptance failed'; END IF;
END $$;
RESET ROLE;
COMMIT;
SELECT enabled,future_schedule_coverage_verified,cutover_on FROM public.billing_runtime_control;
