/**
 * エクスポートで選択できるデータ種別と項目（カラム）の定義。
 * key は DB カラム名（ExportData の各行のキー）と対応。label は画面表示用の日本語名。
 */

export type ExportFieldDef = { key: string; label: string }
export type ExportTableDef = {
  key: 'customers' | 'projects' | 'contracts' | 'annual_records' | 'maintenance_responses' | 'periodic_maintenance' | 'prospects' | 'projects_joined'
  label: string
  fields: ExportFieldDef[]
}

export const EXPORT_FIELD_DEFS: ExportTableDef[] = [
  {
    key: 'customers', label: '顧客',
    fields: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '顧客名' },
      { key: 'name_kana', label: 'フリガナ' },
      { key: 'company_name', label: '会社名' },
      { key: 'is_corporate', label: '法人区分' },
      { key: 'email', label: 'メール' },
      { key: 'phone', label: '電話番号' },
      { key: 'postal_code', label: '郵便番号' },
      { key: 'address', label: '住所' },
      { key: 'notes', label: '備考' },
      { key: 'created_at', label: '登録日時' },
    ],
  },
  {
    key: 'projects', label: '発電所',
    fields: [
      { key: 'id', label: 'ID' },
      { key: 'customer_id', label: '顧客ID' },
      { key: 'project_no', label: '案件番号' },
      { key: 'project_name', label: '案件名' },
      { key: 'plant_name', label: '発電所名' },
      { key: 'site_postal_code', label: '設置場所 郵便番号' },
      { key: 'site_prefecture', label: '都道府県' },
      { key: 'site_address', label: '住所' },
      { key: 'latitude', label: '緯度' },
      { key: 'longitude', label: '経度' },
      { key: 'google_coordinates', label: 'Google座標' },
      { key: 'panel_kw', label: 'パネルKW' },
      { key: 'panel_count', label: 'パネル枚数' },
      { key: 'panel_maker', label: 'パネルメーカー' },
      { key: 'panel_model', label: 'パネル型式' },
      { key: 'panel_notes', label: 'パネル備考' },
      { key: 'pcs_kw', label: 'パワコンKW' },
      { key: 'pcs_count', label: 'パワコン台数' },
      { key: 'pcs_maker', label: 'パワコンメーカー' },
      { key: 'pcs_model', label: 'パワコン型式' },
      { key: 'pcs_notes', label: 'パワコン備考' },
      { key: 'grid_id', label: '設備ID' },
      { key: 'grid_certified_at', label: '認定日' },
      { key: 'fit_period', label: 'FIT（円）' },
      { key: 'fit_term_years', label: 'FIT期間（年・旧）' },
      { key: 'fit_end_date', label: 'FIT満了年月' },
      { key: 'power_supply_start_date', label: '受給開始日' },
      { key: 'customer_number', label: 'お客様番号' },
      { key: 'generation_point_id', label: '受給地点番号' },
      { key: 'meter_reading_day', label: '検針日' },
      { key: 'monitoring_system', label: '遠隔監視メーカー' },
      { key: 'monitoring_model', label: '遠隔監視型式' },
      { key: 'monitoring_id', label: '遠隔監視ID' },
      { key: 'monitoring_user', label: '遠隔監視ユーザー' },
      { key: 'monitoring_pw', label: '遠隔監視パスワード' },
      { key: 'has_4g', label: '4G対応' },
      { key: 'monitoring_notes', label: '遠隔監視備考' },
      { key: 'key_number', label: '鍵番号' },
      { key: 'local_association', label: '自治会' },
      { key: 'old_owner', label: '旧所有者' },
      { key: 'sales_company', label: '販売会社' },
      { key: 'referrer', label: '紹介者（旧）' },
      { key: 'customer_referrer', label: '顧客紹介者' },
      { key: 'project_referrer', label: '案件紹介者' },
      { key: 'power_change_date', label: '電力変更日' },
      { key: 'handover_date', label: '引渡日' },
      { key: 'sales_price', label: '設備代' },
      { key: 'reference_price', label: '参考価格' },
      { key: 'land_cost', label: '土地代' },
      { key: 'amuras_member_no', label: 'アプラス会員番号' },
      { key: 'notes', label: '備考' },
      { key: 'created_at', label: '登録日時' },
    ],
  },
  {
    key: 'contracts', label: '契約',
    fields: [
      { key: 'id', label: 'ID' },
      { key: 'project_id', label: '発電所ID' },
      { key: 'billing_method', label: '請求方法' },
      { key: 'billing_due_day', label: '請求基準日（旧）' },
      { key: 'billing_amount_ex', label: '請求額（税抜/回）' },
      { key: 'billing_amount_inc', label: '請求額（税込/回）' },
      { key: 'annual_maintenance_ex', label: '年次保守料（税抜）' },
      { key: 'annual_maintenance_inc', label: '年次保守料（税込）' },
      { key: 'land_cost_monthly', label: '土地賃料（年間）' },
      { key: 'insurance_fee', label: '火災保険料' },
      { key: 'other_fee', label: 'その他費用' },
      { key: 'communication_fee', label: '通信費' },
      { key: 'local_association_fee', label: '自治会費' },
      { key: 'transfer_fee', label: '振替手数料（旧）' },
      { key: 'transfer_account', label: '振替口座' },
      { key: 'sale_contract_date', label: '売買契約日' },
      { key: 'equipment_contract_date', label: '設備契約日' },
      { key: 'land_contract_date', label: '土地契約日' },
      { key: 'ownership_transfer_date', label: '所有権移転日' },
      { key: 'maintenance_contract_date', label: '保守契約日' },
      { key: 'sales_to_neosys', label: '販売店→ネオシス' },
      { key: 'neosys_to_referrer', label: 'ネオシス→紹介者' },
      { key: 'contractor_name', label: '契約者名（廃止予定）' },
      { key: 'billing_count', label: '年間請求回数' },
      { key: 'subcontractor', label: '保守委託先' },
      { key: 'subcontract_fee_ex', label: '委託料（税抜）' },
      { key: 'subcontract_fee_inc', label: '委託料（税込）' },
      { key: 'subcontract_billing_day', label: '委託請求日' },
      { key: 'subcontract_start_date', label: '委託開始日' },
      { key: 'maintenance_start_date', label: '保守開始日' },
      { key: 'maintenance_contractor', label: '受託会社' },
      { key: 'plan_inspection', label: '点検プラン' },
      { key: 'plan_weeding', label: '除草プラン' },
      { key: 'plan_emergency', label: '駆けつけプラン' },
      { key: 'notes', label: '備考（請求情報）' },
      { key: 'equipment_contract_notes', label: '設備契約備考' },
      { key: 'land_contract_notes', label: '土地契約備考' },
      { key: 'maintenance_contract_notes', label: '保守契約備考' },
      { key: 'maintenance_content_notes', label: '保守内容備考' },
      { key: 'subcontract_notes', label: '委託契約備考' },
      { key: 'has_meti_setup_report', label: '経産省 設置報告有無' },
      { key: 'has_meti_periodic_report', label: '経産省 定期報告有無' },
      { key: 'meti_setup_report_date', label: '設置報告 申請日' },
      { key: 'meti_setup_report_status', label: '設置報告 ステータス' },
      { key: 'has_issuance_fee', label: '発行手数料 有無' },
      { key: 'issuance_fee_ex', label: '発行手数料（税抜）' },
      { key: 'issuance_fee_inc', label: '発行手数料（税込）' },
      { key: 'has_transfer_fee', label: '振替手数料 有無' },
      { key: 'transfer_fee_ex', label: '振替手数料（税抜）' },
      { key: 'transfer_fee_inc', label: '振替手数料（税込）' },
      { key: 'billing_schedule_days', label: '請求予定日リスト' },
      { key: 'billing_amount_overrides', label: '金額上書き（回別）' },
      { key: 'billing_item_flags', label: '請求対象フラグ' },
      { key: 'created_at', label: '登録日時' },
    ],
  },
  {
    key: 'annual_records', label: '請求記録',
    fields: [
      { key: 'id', label: 'ID' },
      { key: 'contract_id', label: '契約ID' },
      { key: 'year', label: '年度' },
      { key: 'billing_scheduled_date', label: '請求予定日' },
      { key: 'billing_date', label: '請求日' },
      { key: 'payment_due_date', label: '入金予定日' },
      { key: 'received_date', label: '入金日' },
      { key: 'line_items', label: '請求明細' },
      { key: 'payments', label: '分割入金記録' },
      { key: 'maintenance_record', label: '保守記録メモ' },
      { key: 'escort_record', label: '駆付記録' },
      { key: 'transfer_failed', label: '振替不能フラグ' },
      { key: 'status', label: '状態' },
      { key: 'created_at', label: '登録日時' },
      { key: 'updated_at', label: '更新日時' },
    ],
  },
  {
    key: 'maintenance_responses', label: '保守対応',
    fields: [
      { key: 'id', label: 'ID' },
      { key: 'response_no', label: '管理番号' },
      { key: 'project_id', label: '発電所ID' },
      { key: 'status', label: '状態' },
      { key: 'inquiry_date', label: '問合日' },
      { key: 'occurrence_date', label: '発生日' },
      { key: 'target_area', label: '対象箇所' },
      { key: 'serial_number', label: '製造番号' },
      { key: 'situation', label: '状況' },
      { key: 'response_content', label: '対応' },
      { key: 'report', label: '報告' },
      { key: 'created_at', label: '登録日時' },
    ],
  },
  {
    key: 'periodic_maintenance', label: '定期保守',
    fields: [
      { key: 'id', label: 'ID' },
      { key: 'project_id', label: '発電所ID' },
      { key: 'record_date', label: '実施日' },
      { key: 'work_type', label: '作業種別' },
      { key: 'content', label: '内容' },
      { key: 'status', label: 'ステータス' },
      { key: 'created_at', label: '登録日時' },
    ],
  },
  {
    key: 'prospects', label: '見込み',
    fields: [
      { key: 'id', label: 'ID' },
      { key: 'customer_name', label: '顧客名' },
      { key: 'customer_name_kana', label: 'フリガナ' },
      { key: 'project_name', label: '発電所名' },
      { key: 'loan_company', label: '融資会社' },
      { key: 'equipment', label: '設備費' },
      { key: 'land_cost', label: '土地費' },
      { key: 'loan_amount', label: '融資額' },
      { key: 'apply_status', label: '申請状況' },
      { key: 'contract_status', label: '契約状況' },
      { key: 'apply_tasks', label: '申請タスク' },
      { key: 'contract_tasks', label: '契約タスク' },
      { key: 'apply_sub_tasks', label: '申請サブタスク' },
      { key: 'contract_sub_tasks', label: '契約サブタスク' },
      { key: 'apply_memo', label: '申請メモ' },
      { key: 'contract_memo', label: '契約メモ' },
      { key: 'site_address', label: '住所' },
      { key: 'google_coordinates', label: 'Google座標' },
      { key: 'panel_kw', label: 'パネルKW' },
      { key: 'sales_company', label: '販売会社' },
      { key: 'referrer', label: '紹介者' },
      { key: 'lead_date', label: 'リード日' },
      { key: 'apply_submit_date', label: '申請提出日' },
      { key: 'apply_result_date', label: '申請結果日' },
      { key: 'sale_contract_date', label: '売買契約日' },
      { key: 'land_contract_date', label: '土地契約日' },
      { key: 'loan_apply_date', label: '融資申込日' },
      { key: 'handover_date', label: '引渡日' },
      { key: 'converted_customer_id', label: '成約顧客ID' },
      { key: 'converted_at', label: '成約日時' },
      { key: 'created_at', label: '登録日時' },
    ],
  },
]

/**
 * 結合ビュー「発電所まとめ」: 1行 = 1発電所で、顧客名＋発電所＋契約（金額系含む）の項目を
 * 横断して選べる。キーは "customer.name" / "project.plant_name" / "contract.annual_maintenance_inc" 形式。
 * 発電所名と金額（保守料・土地代など）を1つの表で出す用途向け。
 */
export const JOINED_TABLE_KEY = 'projects_joined'

function joinedLabel(src: 'project' | 'contract', f: ExportFieldDef): string {
  if (f.key === 'id') return src === 'project' ? '発電所ID' : '契約ID'
  if (f.key === 'created_at') return src === 'project' ? '発電所 登録日時' : '契約 登録日時'
  if (src === 'project' && f.key === 'notes') return '備考（発電所）'
  return f.label
}

const projectsDef = EXPORT_FIELD_DEFS.find(t => t.key === 'projects')!
const contractsDef = EXPORT_FIELD_DEFS.find(t => t.key === 'contracts')!

export const JOINED_EXPORT_DEF: ExportTableDef = {
  key: 'projects_joined',
  label: '発電所まとめ（顧客・契約と結合）',
  fields: [
    { key: 'customer.name', label: '顧客名' },
    { key: 'customer.company_name', label: '会社名' },
    // customer_id / project_id は結合済みなので冗長。除外する
    ...projectsDef.fields.filter(f => f.key !== 'customer_id').map(f => ({ key: `project.${f.key}`, label: joinedLabel('project', f) })),
    ...contractsDef.fields.filter(f => f.key !== 'project_id').map(f => ({ key: `contract.${f.key}`, label: joinedLabel('contract', f) })),
  ],
}
